const test=require("node:test");const assert=require("node:assert/strict");const{createDSP,nativeVersion}=require("../dist/index.js");
function makeDSP(format="f32",channels=2){return createDSP({sampleRate:48000,channels,format});}
function samples(n=480){const b=Buffer.alloc(n*4);const v=new Float32Array(b.buffer,b.byteOffset,n);for(let i=0;i<n;i++)v[i]=.95*Math.sin(2*Math.PI*1000*i/48000);return b;}
function floats(buffer,n){return new Float32Array(buffer.buffer,buffer.byteOffset,n);}
test("native addon loads through N-API and Phase 7 dynamics build",()=>assert.equal(nativeVersion(),"0.8.0-phase7-dynamics"));
test("limiter constrains peaks and supports runtime release",()=>{const d=makeDSP("f32",1);d.setLimiter({threshold:-6,release:30});const input=Buffer.alloc(64*4);floats(input,64).fill(.99);const out=floats(d.process(input),64);assert.ok(Math.max(...out)<=.51);d.clearLimiter();const cleared=floats(d.process(input),64);assert.ok(Math.max(...cleared)>.9);d.destroy();});
test("compressor reduces level above threshold",()=>{const d=makeDSP("f32",1);d.setCompressor({threshold:-18,ratio:4,attack:1,release:50});const out=floats(d.process(samples(960)),960);assert.ok(Math.max(...out)<.95);d.clearCompressor();d.destroy();});
test("soft clip is bounded and can be disabled",()=>{const d=makeDSP("f32",1);const input=Buffer.alloc(32*4);floats(input,32).fill(1);d.setSoftClip(true,4);const out=floats(d.process(input),32);for(const x of out)assert.ok(Math.abs(x)<=1);d.setSoftClip(false);assert.deepEqual(d.process(input),input);d.destroy();});
test("documented dynamics order is compressor -> limiter -> soft clip",()=>{const d=makeDSP("f32",1);const input=Buffer.alloc(4800*4);floats(input,4800).fill(1);d.setCompressor({threshold:-18,ratio:4,attack:1,release:100});d.setLimiter({threshold:-6,release:30});d.setSoftClip(true,20);const out=floats(d.process(input),4800);assert.ok(Math.max(...out)>.9);d.destroy();});
test("volume boost reaches filters before output clamp",()=>{const d=makeDSP("f32",1);d.setVolume(2);d.setBiquad({type:"peaking",frequency:1000,q:1,gain:-24});const out=floats(d.process(samples(4800)),4800);assert.ok(Math.max(...out)<.2);d.destroy();});
test("native volume, mute, and pan boundaries reject invalid values",()=>{const d=makeDSP("f32",2);assert.throws(()=>d.setVolume(NaN),/volume must be between 0 and 4/);assert.throws(()=>d.setVolume(5),/volume must be between 0 and 4/);assert.throws(()=>d.setPan(Infinity),/pan must be between -1 and 1/);assert.throws(()=>d.setPan(2),/pan must be between -1 and 1/);assert.throws(()=>d.setMute(1),/muted must be boolean/);d.destroy();});
test("dynamics preserve graph, EQ, and legacy filter APIs",()=>{const d=makeDSP("f32",2);d.addEQ("eq",[{type:"peaking",frequency:1000,q:1,gain:3}]);d.addBiquad("lp",{type:"lowPass",frequency:12000});d.setFilterOrder(["eq","lp"]);d.setCompressor({threshold:-12,ratio:2});d.setLimiter({threshold:-1});d.setSoftClip(true,2);assert.equal(d.process(samples(480)).length,480*4);d.updateBiquad("lp",{type:"lowPass",frequency:10000});d.updateEQ("eq",[{type:"peaking",frequency:1500,q:.8,gain:2}]);assert.equal(d.process(samples(480)).length,480*4);d.reset();assert.equal(d.process(samples(64)).length,64*4);d.destroy();});
test("invalid dynamics parameters are rejected",()=>{const d=makeDSP();assert.throws(()=>d.setLimiter({threshold:1}),/invalid limiter/);assert.throws(()=>d.setCompressor({ratio:.5}),/invalid compressor/);assert.throws(()=>d.setSoftClip(true,21),/soft clip drive/);d.destroy();});
