const test = require("node:test");
const assert = require("node:assert/strict");
const { createDSP, nativeVersion } = require("../dist/index.js");
function makeDSP(format = "s16", channels = 2) { return createDSP({ sampleRate: 48000, channels, format }); }
function rms(v) { return Math.sqrt(v.reduce((s,x)=>s+x*x,0)/v.length); }
test("native addon loads through N-API and Phase 5 EQ build", () => assert.equal(nativeVersion(), "0.6.0-phase5-eq"));
test("multi-band EQ applies shelf and peaking bands", () => { const dsp=makeDSP("f32",1); dsp.setEQ([{type:"lowShelf",frequency:100,gain:6},{type:"peaking",frequency:1000,q:1,gain:4},{type:"highShelf",frequency:8000,gain:-3}]); const input=Buffer.alloc(960*4); const v=new Float32Array(input.buffer,input.byteOffset,960); for(let i=0;i<v.length;i++)v[i]=.2*Math.sin(2*Math.PI*1000*i/48000); const out=dsp.process(input); assert.equal(out.length,input.length); assert.notDeepEqual(out,input); dsp.destroy(); });
test("multi-band EQ has measurable peaking response", () => { const dsp=makeDSP("f32",1); dsp.setEQ([{type:"peaking",frequency:1000,q:1,gain:6}]); const makeTone=f=>{const b=Buffer.alloc(4096*4),v=new Float32Array(b.buffer,b.byteOffset,4096);for(let i=0;i<v.length;i++)v[i]=.2*Math.sin(2*Math.PI*f*i/48000);return new Float32Array(dsp.process(b).buffer,0,4096);}; const at1=rms(makeTone(1000).slice(1024)); dsp.reset(); dsp.setEQ([{type:"peaking",frequency:1000,q:1,gain:6}]); const at8=rms(makeTone(8000).slice(1024)); assert.ok(at1>at8*1.4,`expected boost near center: ${at1} vs ${at8}`); dsp.destroy(); });
test("EQ preserves per-band state when parameters change in place", () => { const dsp=makeDSP("f32",1); dsp.setEQ([{type:"peaking",frequency:1000,q:1,gain:0}]); const input=Buffer.alloc(480*4); const v=new Float32Array(input.buffer,input.byteOffset,480); for(let i=0;i<v.length;i++)v[i]=i===0?1:0; dsp.process(input); dsp.setEQ([{type:"peaking",frequency:1200,q:1,gain:6}]); const out=new Float32Array(dsp.process(input).buffer,0,480); assert.ok(Math.abs(out[0])<.5,"updated filter should retain prior delay state"); assert.ok(out.some(x=>Math.abs(x)>1e-6)); dsp.destroy(); });
test("EQ preserves state across consecutive blocks", () => { const dsp=makeDSP("f32",1); dsp.setEQ([{type:"peaking",frequency:1000,q:1,gain:6}]); const input=Buffer.alloc(480*4); const v=new Float32Array(input.buffer,input.byteOffset,480); for(let i=0;i<v.length;i++)v[i]=.2*Math.sin(2*Math.PI*1000*i/48000); const a=dsp.process(input),b=dsp.process(input); assert.notDeepEqual(a,input); assert.notDeepEqual(b,input); dsp.destroy(); });
test("EQ supports stereo and all supported band types", () => { const dsp=makeDSP("f32",2); dsp.setEQ([{type:"lowShelf",frequency:120,gain:3},{type:"peaking",frequency:1000,q:.8,gain:-2},{type:"highShelf",frequency:9000,gain:4}]); const input=Buffer.alloc(128*2*4); assert.equal(dsp.process(input).length,input.length); dsp.destroy(); });
test("EQ validation rejects invalid arrays, types and parameters", () => { const dsp=makeDSP("f32",2); assert.throws(()=>dsp.setEQ({}),/array/); assert.throws(()=>dsp.setEQ([{type:"lowPass",frequency:1000,gain:2}]),/type/); assert.throws(()=>dsp.setEQ([{type:"peaking",frequency:0,gain:2}]),/frequency/); assert.throws(()=>dsp.setEQ([{type:"peaking",frequency:1000,q:0,gain:2}]),/q/); assert.throws(()=>dsp.setEQ([{type:"peaking",frequency:1000,gain:25}]),/gain/); assert.throws(()=>dsp.setEQ(Array.from({length:17},()=>({type:"peaking",frequency:1000,gain:0}))),/16/); dsp.destroy(); });
test("clearEQ and reset restore transparent processing", () => { const dsp=makeDSP("f32",1); const input=Buffer.alloc(256*4); const v=new Float32Array(input.buffer,input.byteOffset,256); for(let i=0;i<v.length;i++)v[i]=Math.sin(i/9)*.2; dsp.setEQ([{type:"peaking",frequency:1200,q:1,gain:6}]); assert.notDeepEqual(dsp.process(input),input); dsp.clearEQ(); assert.deepEqual(dsp.process(input),input); dsp.setEQ([{type:"lowShelf",frequency:100,gain:5}]); dsp.reset(); assert.deepEqual(dsp.process(input),input); dsp.destroy(); });
test("basic filters, biquad, frame validation and lifecycle remain intact", () => { const dsp=makeDSP("s16"); const input=Buffer.alloc(480*4,7); dsp.setVolume(.75); dsp.setPan(-.25); dsp.setBiquad({type:"notch",frequency:1000}); dsp.setEQ([{type:"peaking",frequency:2000,q:1,gain:3}]); assert.equal(dsp.process(input).length,input.length); assert.throws(()=>dsp.process(Buffer.alloc(3)),/aligned/); dsp.destroy(); dsp.destroy(); assert.throws(()=>dsp.setEQ([]),/destroyed/); });
