const test = require("node:test");
const assert = require("node:assert/strict");
const { createDSP, nativeVersion } = require("../dist/index.js");
function makeDSP(format = "s16", channels = 2) { return createDSP({ sampleRate: 48000, channels, format }); }
test("native addon loads through N-API and Phase 4 biquad build", () => assert.equal(nativeVersion(), "0.5.0-phase4-biquad"));
test("low-pass attenuates a high-frequency signal", () => { const dsp=makeDSP("f32",1); dsp.setBiquad({type:"lowPass",frequency:1000,q:.707}); const input=Buffer.alloc(480*4); const v=new Float32Array(input.buffer,input.byteOffset,480); for(let i=0;i<v.length;i++)v[i]=Math.sin(2*Math.PI*8000*i/48000); const out=new Float32Array(dsp.process(input).buffer,0,480); const rms=Math.sqrt(out.slice(240).reduce((s,x)=>s+x*x,0)/240); assert.ok(rms<.2,`unexpected RMS ${rms}`); dsp.destroy(); });
test("high-pass attenuates DC", () => { const dsp=makeDSP("f32",1); dsp.setBiquad({type:"highPass",frequency:1000,q:.707}); const input=Buffer.alloc(480*4); new Float32Array(input.buffer,input.byteOffset,480).fill(.75); const out=new Float32Array(dsp.process(input).buffer,0,480); assert.ok(Math.abs(out[479])<.02); dsp.destroy(); });
test("peaking EQ processes consecutive blocks with preserved state", () => { const dsp=makeDSP("f32",1); dsp.setBiquad({type:"peaking",frequency:1000,q:1,gain:6}); const input=Buffer.alloc(480*4); const v=new Float32Array(input.buffer,input.byteOffset,480); for(let i=0;i<v.length;i++)v[i]=.2*Math.sin(2*Math.PI*1000*i/48000); const first=dsp.process(input),second=dsp.process(input); assert.notDeepEqual(first,input); assert.notDeepEqual(second,input); dsp.destroy(); });
test("all supported biquad types configure and process", () => { for(const type of ["lowPass","highPass","bandPass","notch","peaking","lowShelf","highShelf"]){const dsp=makeDSP("f32",2); dsp.setBiquad({type,frequency:1000,q:1,gain:3}); const input=Buffer.alloc(64*2*4); assert.equal(dsp.process(input).length,input.length); dsp.destroy();} });
test("biquad validation rejects unsafe parameters", () => { const dsp=makeDSP("f32",2); assert.throws(()=>dsp.setBiquad({type:"wat",frequency:1000}),/type/); assert.throws(()=>dsp.setBiquad({type:"lowPass",frequency:0}),/frequency/); assert.throws(()=>dsp.setBiquad({type:"lowPass",frequency:24000}),/frequency/); assert.throws(()=>dsp.setBiquad({type:"lowPass",frequency:1000,q:0}),/q/); assert.throws(()=>dsp.setBiquad({type:"peaking",frequency:1000,gain:25}),/gain/); dsp.destroy(); });
test("clearBiquad and reset restore transparent processing", () => { const dsp=makeDSP("f32",1); const input=Buffer.alloc(128*4); const v=new Float32Array(input.buffer,input.byteOffset,128); for(let i=0;i<v.length;i++)v[i]=Math.sin(i/7)*.5; dsp.setBiquad({type:"lowPass",frequency:1000,q:.7}); assert.notDeepEqual(dsp.process(input),input); dsp.clearBiquad(); assert.deepEqual(dsp.process(input),input); dsp.setBiquad({type:"highPass",frequency:2000,q:.7}); dsp.reset(); assert.deepEqual(dsp.process(input),input); dsp.destroy(); });
test("basic filters, frame validation and lifecycle remain intact", () => { const dsp=makeDSP("s16"); const input=Buffer.alloc(480*4,7); dsp.setVolume(.75); dsp.setPan(-.25); dsp.setBiquad({type:"notch",frequency:1000}); assert.equal(dsp.process(input).length,input.length); assert.throws(()=>dsp.process(Buffer.alloc(3)),/aligned/); dsp.destroy(); dsp.destroy(); assert.throws(()=>dsp.setBiquad({type:"lowPass",frequency:1000}),/destroyed/); });
