#include <napi.h>
#include "miniaudio.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>
namespace {
struct Biquad{std::string type;float b0=1,b1=0,b2=0,a1=0,a2=0;std::vector<float>x1,x2,y1,y2;bool enabled=false;};
struct DSPContext{uint32_t sample_rate,channels,bytes_per_sample;ma_format format;ma_data_converter converter;bool converter_initialized,destroyed;float volume,pan;bool muted;Biquad biquad;std::vector<Biquad> eq;};
DSPContext*C(const Napi::CallbackInfo&i){auto*c=i.This().Get("_context").As<Napi::External<DSPContext>>().Data();if(!c||c->destroyed)throw Napi::Error::New(i.Env(),"AudioDSP instance has been destroyed");return c;}
void IC(DSPContext*c){auto cfg=ma_data_converter_config_init(c->format,c->format,c->channels,c->channels,c->sample_rate,c->sample_rate);if(ma_data_converter_init(&cfg,nullptr,&c->converter)!=MA_SUCCESS)throw std::runtime_error("miniaudio data converter initialization failed");c->converter_initialized=true;}
float LG(float p){return p>0?1-p:1;}float RG(float p){return p<0?1+p:1;}float CL(float v){return std::max(-1.f,std::min(1.f,v));}int16_t S16(float v){return static_cast<int16_t>(std::lrintf(std::max(-32768.f,std::min(32767.f,v))));}
void RS(Biquad&b,uint32_t ch){b.x1.assign(ch,0);b.x2.assign(ch,0);b.y1.assign(ch,0);b.y2.assign(ch,0);}
void CFG(Biquad&b,uint32_t sr,const std::string&t,double f,double q,double g,uint32_t ch){b.type=t;double pi=std::acos(-1),w=2*pi*f/sr,cs=std::cos(w),sn=std::sin(w),a=sn/(2*q),A=std::pow(10,g/40),bt=2*std::sqrt(A)*a,b0,b1,b2,a0,a1,a2;if(t=="lowPass"){b0=(1-cs)/2;b1=1-cs;b2=b0;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="highPass"){b0=(1+cs)/2;b1=-(1+cs);b2=b0;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="bandPass"){b0=a;b1=0;b2=-a;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="notch"){b0=1;b1=-2*cs;b2=1;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="peaking"){b0=1+a*A;b1=-2*cs;b2=1-a*A;a0=1+a/A;a1=-2*cs;a2=1-a/A;}else if(t=="lowShelf"){b0=A*((A+1)-(A-1)*cs+bt);b1=2*A*((A-1)-(A+1)*cs);b2=A*((A+1)-(A-1)*cs-bt);a0=(A+1)+(A-1)*cs+bt;a1=-2*((A-1)+(A+1)*cs);a2=(A+1)+(A-1)*cs-bt;}else{b0=A*((A+1)+(A-1)*cs+bt);b1=-2*A*((A-1)+(A+1)*cs);b2=A*((A+1)+(A-1)*cs-bt);a0=(A+1)-(A-1)*cs+bt;a1=2*((A-1)-(A+1)*cs);a2=(A+1)-(A-1)*cs-bt;}b.b0=b0/a0;b.b1=b1/a0;b.b2=b2/a0;b.a1=a1/a0;b.a2=a2/a0;b.enabled=true;RS(b,ch);}
float BS(Biquad&b,size_t ch,float x){float y=b.b0*x+b.b1*b.x1[ch]+b.b2*b.x2[ch]-b.a1*b.y1[ch]-b.a2*b.y2[ch];b.x2[ch]=b.x1[ch];b.x1[ch]=x;b.y2[ch]=b.y1[ch];b.y1[ch]=y;return y;}
void Apply(DSPContext*c,uint8_t*d,size_t fr){float gain=c->muted?0:c->volume,lg=gain*LG(c->pan),rg=gain*RG(c->pan);auto one=[&](size_t ch,float x){float g=(c->channels>1&&ch==0)?lg:(c->channels>1&&ch==1?rg:gain);x=CL(x*g);if(c->biquad.enabled)x=CL(BS(c->biquad,ch,x));for(auto&b:c->eq)x=CL(BS(b,ch,x));return x;};if(c->format==ma_format_s16){auto*s=reinterpret_cast<int16_t*>(d);for(size_t f=0;f<fr;f++)for(uint32_t ch=0;ch<c->channels;ch++)s[f*c->channels+ch]=S16(one(ch,s[f*c->channels+ch]/32768.f)*32768.f);}else{auto*s=reinterpret_cast<float*>(d);for(size_t f=0;f<fr;f++)for(uint32_t ch=0;ch<c->channels;ch++)s[f*c->channels+ch]=one(ch,s[f*c->channels+ch]);}}
Napi::Value Process(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);if(i.Length()<1||!i[0].IsBuffer())throw Napi::TypeError::New(e,"process() requires a Buffer");auto in=i[0].As<Napi::Buffer<uint8_t>>();size_t fb=(size_t)c->channels*c->bytes_per_sample;if(in.Length()%fb)throw Napi::RangeError::New(e,"input buffer is not aligned to complete audio frames");size_t fr=in.Length()/fb;auto out=Napi::Buffer<uint8_t>::New(e,in.Length());if(!fr)return out;ma_uint64 inf=fr,outf=fr;if(ma_data_converter_process_pcm_frames(&c->converter,in.Data(),&inf,out.Data(),&outf)!=MA_SUCCESS)throw Napi::Error::New(e,"miniaudio failed to process PCM frames");if(inf!=fr||outf!=fr)throw Napi::Error::New(e,"miniaudio processed an unexpected frame count");Apply(c,out.Data(),fr);return out;}
Napi::Value SetVolume(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);double v=i[0].As<Napi::Number>().DoubleValue();if(!std::isfinite(v)||v<0||v>4)throw Napi::RangeError::New(e,"volume must be a finite number from 0 to 4");c->volume=v;return e.Undefined();}Napi::Value SetMute(const Napi::CallbackInfo&i){auto*c=C(i);c->muted=i[0].As<Napi::Boolean>().Value();return i.Env().Undefined();}Napi::Value SetPan(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);if(c->channels<2)throw Napi::Error::New(e,"pan requires at least 2 channels");double v=i[0].As<Napi::Number>().DoubleValue();if(!std::isfinite(v)||v<-1||v>1)throw Napi::RangeError::New(e,"pan must be a finite number from -1 to 1");c->pan=v;return e.Undefined();}
Napi::Value SetBiquad(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);auto o=i[0].As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?0.7071067811865476:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").IsUndefined()?0:o.Get("gain").As<Napi::Number>().DoubleValue();if(!std::isfinite(f)||f<=0||f>=c->sample_rate/2.0||!std::isfinite(q)||q<=0||!std::isfinite(g)||g<-24||g>24)throw Napi::RangeError::New(e,"invalid biquad parameters");CFG(c->biquad,c->sample_rate,t,f,q,g,c->channels);return e.Undefined();}
Napi::Value ClearBiquad(const Napi::CallbackInfo&i){auto*c=C(i);c->biquad.enabled=false;RS(c->biquad,c->channels);return i.Env().Undefined();}
Napi::Value SetEQ(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);if(i.Length()<1||!i[0].IsArray())throw Napi::TypeError::New(e,"setEQ() requires an array");auto a=i[0].As<Napi::Array>();if(a.Length()>16)throw Napi::RangeError::New(e,"EQ supports at most 16 bands");std::vector<Biquad>next;next.reserve(a.Length());for(uint32_t k=0;k<a.Length();k++){auto o=a.Get(k).As<Napi::Object>();auto tv=o.Get("type"),fv=o.Get("frequency"),qv=o.Get("q"),gv=o.Get("gain");if(!tv.IsString()||!fv.IsNumber()||!gv.IsNumber())throw Napi::TypeError::New(e,"EQ band requires type, frequency, and gain");std::string t=tv.As<Napi::String>().Utf8Value();if(t!="lowShelf"&&t!="peaking"&&t!="highShelf")throw Napi::TypeError::New(e,"EQ supports lowShelf, peaking, and highShelf");double f=fv.As<Napi::Number>().DoubleValue(),q=qv.IsUndefined()?0.7071067811865476:qv.As<Napi::Number>().DoubleValue(),g=gv.As<Napi::Number>().DoubleValue();if(!std::isfinite(f)||f<=0||f>=c->sample_rate/2.0||!std::isfinite(q)||q<=0||!std::isfinite(g)||g<-24||g>24)throw Napi::RangeError::New(e,"invalid EQ band parameters");Biquad b;CFG(b,c->sample_rate,t,f,q,g,c->channels);if(k<c->eq.size()&&c->eq[k].type==t){b.x1=c->eq[k].x1;b.x2=c->eq[k].x2;b.y1=c->eq[k].y1;b.y2=c->eq[k].y2;}next.push_back(std::move(b));}c->eq.swap(next);return e.Undefined();}
Napi::Value ClearEQ(const Napi::CallbackInfo&i){auto*c=C(i);c->eq.clear();return i.Env().Undefined();}
Napi::Value Reset(const Napi::CallbackInfo&i){auto*c=C(i);if(c->converter_initialized){ma_data_converter_uninit(&c->converter,nullptr);c->converter_initialized=false;}IC(c);c->volume=1;c->muted=false;c->pan=0;c->biquad=Biquad{};RS(c->biquad,c->channels);c->eq.clear();return i.Env().Undefined();}
Napi::Value Destroy(const Napi::CallbackInfo&i){auto*c=i.This().Get("_context").As<Napi::External<DSPContext>>().Data();if(c&&!c->destroyed){if(c->converter_initialized)ma_data_converter_uninit(&c->converter,nullptr);c->converter_initialized=false;c->destroyed=true;}return i.Env().Undefined();}void Finalize(Napi::Env,DSPContext*c){if(c){if(c->converter_initialized)ma_data_converter_uninit(&c->converter,nullptr);delete c;}}
Napi::Value CreateDSP(const Napi::CallbackInfo&i){auto e=i.Env();auto o=i[0].As<Napi::Object>();double sr=o.Get("sampleRate").As<Napi::Number>().DoubleValue(),ch=o.Get("channels").As<Napi::Number>().DoubleValue();std::string fmt=o.Get("format").As<Napi::String>().Utf8Value();if(!(sr>0)||sr>std::numeric_limits<uint32_t>::max()||sr!=static_cast<uint32_t>(sr))throw Napi::RangeError::New(e,"sampleRate must be a positive integer");if(!(ch>=1)||ch>8||ch!=static_cast<uint32_t>(ch))throw Napi::RangeError::New(e,"channels must be an integer from 1 to 8");if(fmt!="s16"&&fmt!="f32")throw Napi::TypeError::New(e,"format must be s16 or f32");auto*c=new DSPContext{(uint32_t)sr,(uint32_t)ch,fmt=="s16"?2u:4u,fmt=="s16"?ma_format_s16:ma_format_f32,{},false,false,1,0,false,{},{}};try{IC(c);RS(c->biquad,c->channels);}catch(const std::exception&x){delete c;throw Napi::Error::New(e,x.what());}auto d=Napi::Object::New(e);d.Set("_context",Napi::External<DSPContext>::New(e,c,Finalize));d.Set("process",Napi::Function::New(e,Process));d.Set("setVolume",Napi::Function::New(e,SetVolume));d.Set("setMute",Napi::Function::New(e,SetMute));d.Set("setPan",Napi::Function::New(e,SetPan));d.Set("setBiquad",Napi::Function::New(e,SetBiquad));d.Set("clearBiquad",Napi::Function::New(e,ClearBiquad));d.Set("setEQ",Napi::Function::New(e,SetEQ));d.Set("clearEQ",Napi::Function::New(e,ClearEQ));d.Set("reset",Napi::Function::New(e,Reset));d.Set("destroy",Napi::Function::New(e,Destroy));return d;}
Napi::Value Version(const Napi::CallbackInfo&i){return Napi::String::New(i.Env(),"0.6.0-phase5-eq");}Napi::Object Init(Napi::Env e,Napi::Object x){x.Set("version",Napi::Function::New(e,Version));x.Set("createDSP",Napi::Function::New(e,CreateDSP));return x;}}
NODE_API_MODULE(audio_dsp,Init)
