#include <napi.h>
#include "miniaudio.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <limits>
#include <string>
#include <vector>
namespace {
constexpr double DQ=0.7071067811865476;
struct B{std::string type;float b0=1,b1=0,b2=0,a1=0,a2=0;std::vector<float>x1,x2,y1,y2;};
struct N{std::string id,type;std::vector<B> bands;};
struct Ctx{uint32_t sr,ch,bps;ma_format fmt;ma_data_converter conv;bool init=false,dead=false;float vol=1,pan=0;bool mute=false;B biquad;std::vector<B> eq;std::vector<N> graph;};
Ctx*C(const Napi::CallbackInfo&i){auto*c=i.This().Get("_context").As<Napi::External<Ctx>>().Data();if(!c||c->dead)throw Napi::Error::New(i.Env(),"AudioDSP instance has been destroyed");return c;}
void resetState(B&b,uint32_t ch){b.x1.assign(ch,0);b.x2.assign(ch,0);b.y1.assign(ch,0);b.y2.assign(ch,0);}
void initConv(Ctx*c){auto x=ma_data_converter_config_init(c->fmt,c->fmt,c->ch,c->ch,c->sr,c->sr);if(ma_data_converter_init(&x,nullptr,&c->conv)!=MA_SUCCESS)throw std::runtime_error("miniaudio data converter initialization failed");c->init=true;}
void cfg(B&b,uint32_t sr,const std::string&t,double f,double q,double g,uint32_t ch,bool preserve=false,const B*old=nullptr){std::vector<float>x1,x2,y1,y2;if(preserve&&old&&old->type==t){x1=old->x1;x2=old->x2;y1=old->y1;y2=old->y2;}double pi=std::acos(-1),w=2*pi*f/sr,cs=std::cos(w),sn=std::sin(w),a=sn/(2*q),A=std::pow(10,g/40),bt=2*std::sqrt(A)*a,b0,b1,b2,a0,a1,a2;if(t=="lowPass"){b0=(1-cs)/2;b1=1-cs;b2=b0;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="highPass"){b0=(1+cs)/2;b1=-(1+cs);b2=b0;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="bandPass"){b0=a;b1=0;b2=-a;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="notch"){b0=1;b1=-2*cs;b2=1;a0=1+a;a1=-2*cs;a2=1-a;}else if(t=="peaking"){b0=1+a*A;b1=-2*cs;b2=1-a*A;a0=1+a/A;a1=-2*cs;a2=1-a/A;}else if(t=="lowShelf"){b0=A*((A+1)-(A-1)*cs+bt);b1=2*A*((A-1)-(A+1)*cs);b2=A*((A+1)-(A-1)*cs-bt);a0=(A+1)+(A-1)*cs+bt;a1=-2*((A-1)+(A+1)*cs);a2=(A+1)+(A-1)*cs-bt;}else{b0=A*((A+1)+(A-1)*cs+bt);b1=-2*A*((A-1)+(A+1)*cs);b2=A*((A+1)+(A-1)*cs-bt);a0=(A+1)-(A-1)*cs+bt;a1=2*((A-1)-(A+1)*cs);a2=(A+1)-(A-1)*cs-bt;}b.type=t;b.b0=b0/a0;b.b1=b1/a0;b.b2=b2/a0;b.a1=a1/a0;b.a2=a2/a0;if(preserve&&old&&old->type==t){b.x1=x1;b.x2=x2;b.y1=y1;b.y2=y2;}else resetState(b,ch);}
float run(B&b,uint32_t ch,float x){float y=b.b0*x+b.b1*b.x1[ch]+b.b2*b.x2[ch]-b.a1*b.y1[ch]-b.a2*b.y2[ch];b.x2[ch]=b.x1[ch];b.x1[ch]=x;b.y2[ch]=b.y1[ch];b.y1[ch]=y;return y;}
float clamp(float x){return std::max(-1.f,std::min(1.f,x));}
void apply(Ctx*c,uint8_t*d,size_t fr){float g=c->mute?0:c->vol,l=g*(c->pan>0?1-c->pan:1),r=g*(c->pan<0?1+c->pan:1);auto one=[&](uint32_t ch,float x){float q=(c->ch>1?(ch==0?l:(ch==1?r:g)):g);x=clamp(x*q);if(c->graph.empty()){if(!c->biquad.type.empty())x=run(c->biquad,ch,x);for(auto&b:c->eq)x=run(b,ch,x);}else for(auto&n:c->graph)for(auto&b:n.bands)x=run(b,ch,x);return clamp(x);};if(c->fmt==ma_format_s16){auto*s=(int16_t*)d;for(size_t f=0;f<fr;f++)for(uint32_t ch=0;ch<c->ch;ch++)s[f*c->ch+ch]=(int16_t)std::lrintf(std::max(-32768.f,std::min(32767.f,one(ch,s[f*c->ch+ch]/32768.f)*32768.f)));}else{auto*s=(float*)d;for(size_t f=0;f<fr;f++)for(uint32_t ch=0;ch<c->ch;ch++)s[f*c->ch+ch]=one(ch,s[f*c->ch+ch]);}}
Napi::Value Process(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);if(i.Length()<1||!i[0].IsBuffer())throw Napi::TypeError::New(e,"process() requires a Buffer");auto in=i[0].As<Napi::Buffer<uint8_t>>();size_t fb=(size_t)c->ch*c->bps;if(in.Length()%fb)throw Napi::RangeError::New(e,"input buffer is not aligned to complete audio frames");size_t fr=in.Length()/fb;auto out=Napi::Buffer<uint8_t>::New(e,in.Length());if(!fr)return out;ma_uint64 a=fr,z=fr;if(ma_data_converter_process_pcm_frames(&c->conv,in.Data(),&a,out.Data(),&z)!=MA_SUCCESS||a!=fr||z!=fr)throw Napi::Error::New(e,"miniaudio failed to process PCM frames");apply(c,out.Data(),fr);return out;}
void ensureId(Ctx*c,const std::string&id){for(auto&n:c->graph)if(n.id==id)throw std::runtime_error("filter id already exists: "+id);}
Napi::Value SetVolume(const Napi::CallbackInfo&i){auto*c=C(i);c->vol=i[0].As<Napi::Number>().DoubleValue();return i.Env().Undefined();}Napi::Value SetMute(const Napi::CallbackInfo&i){auto*c=C(i);c->mute=i[0].As<Napi::Boolean>().Value();return i.Env().Undefined();}Napi::Value SetPan(const Napi::CallbackInfo&i){auto*c=C(i);c->pan=i[0].As<Napi::Number>().DoubleValue();return i.Env().Undefined();}
Napi::Value SetBiquad(const Napi::CallbackInfo&i){auto e=i.Env();auto*c=C(i);auto o=i[0].As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").IsUndefined()?0:o.Get("gain").As<Napi::Number>().DoubleValue();cfg(c->biquad,c->sr,t,f,q,g,c->ch);return e.Undefined();}
Napi::Value ClearBiquad(const Napi::CallbackInfo&i){auto*c=C(i);c->biquad=B{};resetState(c->biquad,c->ch);return i.Env().Undefined();}
Napi::Value SetEQ(const Napi::CallbackInfo&i){auto*c=C(i);auto a=i[0].As<Napi::Array>();std::vector<B>next;for(uint32_t k=0;k<a.Length();k++){auto o=a.Get(k).As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").As<Napi::Number>().DoubleValue();B b;const B*old=k<c->eq.size()?&c->eq[k]:nullptr;cfg(b,c->sr,t,f,q,g,c->ch,true,old);next.push_back(std::move(b));}c->eq.swap(next);return i.Env().Undefined();}
Napi::Value ClearEQ(const Napi::CallbackInfo&i){C(i)->eq.clear();return i.Env().Undefined();}
Napi::Value AddB(const Napi::CallbackInfo&i){auto*c=C(i);std::string id=i[0].As<Napi::String>().Utf8Value();ensureId(c,id);auto o=i[1].As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").IsUndefined()?0:o.Get("gain").As<Napi::Number>().DoubleValue();N n;n.id=id;n.type="biquad";B b;cfg(b,c->sr,t,f,q,g,c->ch);n.bands.push_back(std::move(b));c->graph.push_back(std::move(n));return i.Env().Undefined();}
Napi::Value AddEQ(const Napi::CallbackInfo&i){auto*c=C(i);std::string id=i[0].As<Napi::String>().Utf8Value();ensureId(c,id);auto a=i[1].As<Napi::Array>();N n;n.id=id;n.type="eq";for(uint32_t k=0;k<a.Length();k++){auto o=a.Get(k).As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").As<Napi::Number>().DoubleValue();B b;cfg(b,c->sr,t,f,q,g,c->ch);n.bands.push_back(std::move(b));}c->graph.push_back(std::move(n));return i.Env().Undefined();}
Napi::Value Remove(const Napi::CallbackInfo&i){auto*c=C(i);std::string id=i[0].As<Napi::String>().Utf8Value();auto it=std::find_if(c->graph.begin(),c->graph.end(),[&](auto&n){return n.id==id;});if(it==c->graph.end())throw Napi::Error::New(i.Env(),"unknown filter id: "+id);c->graph.erase(it);return i.Env().Undefined();}
Napi::Value Order(const Napi::CallbackInfo&i){auto*c=C(i);auto a=i[0].As<Napi::Array>();std::vector<N> next;for(uint32_t k=0;k<a.Length();k++){std::string id=a.Get(k).As<Napi::String>().Utf8Value();auto it=std::find_if(c->graph.begin(),c->graph.end(),[&](auto&n){return n.id==id;});if(it==c->graph.end())throw Napi::Error::New(i.Env(),"unknown filter id: "+id);next.push_back(std::move(*it));}if(next.size()!=c->graph.size())throw Napi::RangeError::New(i.Env(),"filter order must contain every filter id exactly once");c->graph.swap(next);return i.Env().Undefined();}
Napi::Value UpdateB(const Napi::CallbackInfo&i){auto*c=C(i);std::string id=i[0].As<Napi::String>().Utf8Value();auto it=std::find_if(c->graph.begin(),c->graph.end(),[&](auto&n){return n.id==id;});if(it==c->graph.end()||it->type!="biquad")throw Napi::Error::New(i.Env(),"unknown biquad filter id: "+id);auto o=i[1].As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").IsUndefined()?0:o.Get("gain").As<Napi::Number>().DoubleValue();B old=it->bands[0];cfg(it->bands[0],c->sr,t,f,q,g,c->ch,true,&old);return i.Env().Undefined();}
Napi::Value UpdateEQ(const Napi::CallbackInfo&i){auto*c=C(i);std::string id=i[0].As<Napi::String>().Utf8Value();auto it=std::find_if(c->graph.begin(),c->graph.end(),[&](auto&n){return n.id==id;});if(it==c->graph.end()||it->type!="eq")throw Napi::Error::New(i.Env(),"unknown EQ filter id: "+id);auto a=i[1].As<Napi::Array>();if(a.Length()!=it->bands.size())it->bands.resize(a.Length());for(uint32_t k=0;k<a.Length();k++){auto o=a.Get(k).As<Napi::Object>();std::string t=o.Get("type").As<Napi::String>().Utf8Value();double f=o.Get("frequency").As<Napi::Number>().DoubleValue(),q=o.Get("q").IsUndefined()?DQ:o.Get("q").As<Napi::Number>().DoubleValue(),g=o.Get("gain").As<Napi::Number>().DoubleValue();B old=it->bands[k];cfg(it->bands[k],c->sr,t,f,q,g,c->ch,true,&old);}return i.Env().Undefined();}
Napi::Value Reset(const Napi::CallbackInfo&i){auto*c=C(i);if(c->init){ma_data_converter_uninit(&c->conv,nullptr);c->init=false;}initConv(c);c->vol=1;c->pan=0;c->mute=false;c->biquad=B{};resetState(c->biquad,c->ch);c->eq.clear();c->graph.clear();return i.Env().Undefined();}
Napi::Value Destroy(const Napi::CallbackInfo&i){auto*c=i.This().Get("_context").As<Napi::External<Ctx>>().Data();if(c&&!c->dead){if(c->init)ma_data_converter_uninit(&c->conv,nullptr);c->init=false;c->dead=true;}return i.Env().Undefined();}void Final(Napi::Env,Ctx*c){if(c){if(c->init)ma_data_converter_uninit(&c->conv,nullptr);delete c;}}
Napi::Value Create(const Napi::CallbackInfo&i){auto e=i.Env();auto o=i[0].As<Napi::Object>();double sr=o.Get("sampleRate").As<Napi::Number>().DoubleValue(),ch=o.Get("channels").As<Napi::Number>().DoubleValue();std::string fmt=o.Get("format").As<Napi::String>().Utf8Value();auto*c=new Ctx{(uint32_t)sr,(uint32_t)ch,fmt=="s16"?2u:4u,fmt=="s16"?ma_format_s16:ma_format_f32};try{initConv(c);resetState(c->biquad,c->ch);}catch(const std::exception&x){delete c;throw Napi::Error::New(e,x.what());}auto d=Napi::Object::New(e);d.Set("_context",Napi::External<Ctx>::New(e,c,Final));d.Set("process",Napi::Function::New(e,Process));d.Set("setVolume",Napi::Function::New(e,SetVolume));d.Set("setMute",Napi::Function::New(e,SetMute));d.Set("setPan",Napi::Function::New(e,SetPan));d.Set("setBiquad",Napi::Function::New(e,SetBiquad));d.Set("clearBiquad",Napi::Function::New(e,ClearBiquad));d.Set("setEQ",Napi::Function::New(e,SetEQ));d.Set("clearEQ",Napi::Function::New(e,ClearEQ));d.Set("addBiquad",Napi::Function::New(e,AddB));d.Set("addEQ",Napi::Function::New(e,AddEQ));d.Set("removeFilter",Napi::Function::New(e,Remove));d.Set("setFilterOrder",Napi::Function::New(e,Order));d.Set("updateBiquad",Napi::Function::New(e,UpdateB));d.Set("updateEQ",Napi::Function::New(e,UpdateEQ));d.Set("reset",Napi::Function::New(e,Reset));d.Set("destroy",Napi::Function::New(e,Destroy));return d;}
Napi::Value Version(const Napi::CallbackInfo&i){return Napi::String::New(i.Env(),"0.7.0-phase6-filter-graph");}Napi::Object Init(Napi::Env e,Napi::Object x){x.Set("version",Napi::Function::New(e,Version));x.Set("createDSP",Napi::Function::New(e,Create));return x;}}
NODE_API_MODULE(audio_dsp,Init)
